[package]
name = "turbulence"
version = "0.1.0"
authors = ["kyren <kerriganw@gmail.com>"]
edition = "2018"
license = "MIT OR CC-0"

[dependencies]
byteorder = "1.3"
futures = "0.3"
thiserror = "1.0"

[dev-dependencies]
rand = { version = "0.7", features = ["small_rng"] }
